.ORIG x3000
MAIN
    JSR BEGIN_GAME
    JSR PRINT_BOARD
MAIN_LOOP
    JSR GET_VALID_MOVE
    JSR APPLY_MOVE
    JSR IS_GAME_OVER
    ADD R0,R0,#0
    BRz NOT_OVER

    JSR BACKSLASHN
    JSR SAY_WINNER
    HALT
NOT_OVER
    JSR TOGGLE_PLAYER
    JSR BACKSLASHN
    JSR PRINT_BOARD
    BR  MAIN_LOOP
;----^ main stuff---


;----subroutines---

BEGIN_GAME
    AND R0,R0,#0
    ADD R0,R0,#3
    ST R0,A_COUNT
    AND R0,R0,#0
    ADD R0,R0,#5
    ST R0,B_COUNT
    AND R0,R0,#0
    ADD R0,R0,#8
    ST R0,C_COUNT

    AND R0,R0,#0
    ADD  R0,R0,#1
    ST R0,PLAYER
    RET

PRINT_BOARD
    ST R7,SAVE_R7_PB
    LEA R0,STR_ROW_A
    TRAP x22
    LD R1,A_COUNT
    JSR PRINT_STONES
    JSR BACKSLASHN

    LEA R0,STR_ROW_B
    TRAP x22
    LD R1,B_COUNT
    JSR PRINT_STONES
    JSR BACKSLASHN

    LEA R0,STR_ROW_C
    TRAP x22
    LD R1,C_COUNT
    JSR PRINT_STONES
    JSR BACKSLASHN

    LD R7,SAVE_R7_PB
    RET

PRINT_STONES
    ADD R1,R1,#0
    BRz PS_DONE

PS_LOOP
    LD R0,CHR_o
    TRAP x21
    ADD R1,R1,#-1
    BRp PS_LOOP

PS_DONE
    RET

BACKSLASHN
    ST R7,SAVE_R7_NL
    LD R0,NEWLINE_CHAR
    TRAP x21
    LD R7,SAVE_R7_NL
    RET

PROMPT_AND_GET_MOVE
    LD R1,PLAYER
    ADD R1,R1,#-1
    BRz P1_PROMPT

    LEA R0,STR_PROMPT_P2
    TRAP x22
    BR GET_INPUT

P1_PROMPT
    LEA R0,STR_PROMPT_P1
    TRAP x22

GET_INPUT
    TRAP x20
    TRAP x21
    ST R0,MOVE_ROW_CHAR
    TRAP x20
    TRAP x21
    ST R0,MOVE_NUM_CHAR

    LD R0,NEWLINE_CHAR
    TRAP x21
    RET

VALIDATE_MOVE
    LD R1,MOVE_ROW_CHAR

    LD R2,ASCII_A
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz ROW_A_VALID

    LD R2,ASCII_B
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz ROW_B_VALID

    LD R2,ASCII_C
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz ROW_C_VALID
    BR VAL_INVALID

ROW_A_VALID
    LD R4,A_COUNT
    BR CHECK_DIGIT

ROW_B_VALID
    LD R4,B_COUNT
    BR CHECK_DIGIT

ROW_C_VALID
    LD R4,C_COUNT

CHECK_DIGIT
    LD R5,MOVE_NUM_CHAR

    LD R2,ASCII_1
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R5,R3
    BRn VAL_INVALID

    LD R2,ASCII_8
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R5,R3
    BRp VAL_INVALID

    LD R2,ASCII_0
    NOT R3,R2
    ADD R3,R3,#1
    ADD R6,R5,R3
    ST R6,MOVE_NUM

    NOT R3,R6
    ADD R3,R3,#1
    ADD R3,R4,R3
    BRn VAL_INVALID

    AND R0,R0,#0
    ADD R0,R0,#1
    RET

VAL_INVALID
    AND R0,R0,#0
    RET

GET_VALID_MOVE
    ST R7,SAVE_R7_MOVEVALID

MOVEVALID_LOOP
    JSR PROMPT_AND_GET_MOVE
    JSR VALIDATE_MOVE
    ADD R0,R0,#0
    BRp MOVEVALID_OK

    LEA R0,STR_INVALID
    TRAP x22
    JSR BACKSLASHN
    BR MOVEVALID_LOOP

MOVEVALID_OK
    LD R7,SAVE_R7_MOVEVALID
    RET

APPLY_MOVE
    LD R1,MOVE_ROW_CHAR
    LD R5,MOVE_NUM

    LD R2,ASCII_A
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz DO_A

    LD R2,ASCII_B
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz DO_B

    LD R4,C_COUNT
    BR DO_SUB

DO_A
    LD R4,A_COUNT
    BR DO_SUB

DO_B
    LD R4,B_COUNT

DO_SUB
    NOT R6,R5
    ADD R6,R6,#1
    ADD R4,R4,R6

    LD R2,ASCII_A
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz ST_A

    LD R2,ASCII_B
    NOT R3,R2
    ADD R3,R3,#1
    ADD R3,R1,R3
    BRz ST_B

    ST R4,C_COUNT
    RET

ST_A
    ST R4,A_COUNT
    RET

ST_B
    ST R4,B_COUNT
    RET

IS_GAME_OVER
    LD R1,A_COUNT
    LD R2,B_COUNT
    ADD R3,R1,R2
    LD R1,C_COUNT
    ADD R3,R3,R1
    ADD R3,R3,#0
    BRz ALL_ZERO

    AND R0,R0,#0
    RET

ALL_ZERO
    AND R0,R0,#0
    ADD R0,R0,#1
    RET

TOGGLE_PLAYER
    LD R1,PLAYER
    AND R2,R2,#0
    ADD R2,R2,#3
    NOT R3,R1
    ADD R3,R3,#1
    ADD R2,R2,R3
    ST R2,PLAYER
    RET

SAY_WINNER
    LD R1,PLAYER
    ADD R1,R1,#-1
    BRz CURR_IS_1

    LEA R0,STR_P1_WINS
    TRAP x22
    RET

CURR_IS_1
    LEA R0,STR_P2_WINS
    TRAP x22
    RET

NEWLINE_CHAR .FILL x000A
CHR_o .FILL x006F
ASCII_A .FILL x0041
ASCII_B .FILL x0042
ASCII_C .FILL x0043
ASCII_0 .FILL x0030
ASCII_1 .FILL x0031
ASCII_8 .FILL x0038
A_COUNT .FILL #3
B_COUNT .FILL #5
C_COUNT .FILL #8
PLAYER .FILL #1
MOVE_ROW_CHAR .FILL #0
MOVE_NUM_CHAR .FILL #0
MOVE_NUM .FILL #0
SAVE_R7_PB .FILL #0
SAVE_R7_MOVEVALID .FILL #0
SAVE_R7_NL .FILL #0
STR_ROW_A .STRINGZ "ROW A: "
STR_ROW_B .STRINGZ "ROW B: "
STR_ROW_C .STRINGZ "ROW C: "
STR_PROMPT_P1 .STRINGZ "Player 1, choose a row and number of stones: "
STR_PROMPT_P2 .STRINGZ "Player 2, choose a row and number of stones: "
STR_INVALID .STRINGZ "Invalid move. Try again."
STR_P1_WINS .STRINGZ "Player 1 Wins."
STR_P2_WINS .STRINGZ "Player 2 Wins."

.END